"""
Structured LLM response schemas for Meta-Reasoning.

Author: Antigravity
License: MIT
"""

from pydantic import BaseModel, Field


class LLMSubsystemPolicy(BaseModel):
    """
    Schema for a single subsystem's execution policy.
    """

    subsystem_name: str = Field(
        description="Subsystem name, e.g. planning, decision, etc."
    )
    mode: str = Field(description="Execution Mode: RULE, LLM, or HYBRID")
    provider: str | None = Field(None, description="Model provider name")
    model: str | None = Field(None, description="Model identifier name")
    max_tokens: int = Field(10000, description="Allocated token limit budget")
    max_cost_usd: float = Field(0.05, description="Allocated cost limit in USD")
    cache_allowed: bool = Field(True, description="Whether cache reuse is permitted")
    skip_allowed: bool = Field(
        True, description="Whether skip behavior is permitted on success metrics"
    )
    reasoning: str = Field(
        description="Cognitive reasoning justifying the policy assignment"
    )


class LLMMetaOutput(BaseModel):
    """
    Top-level output schema generated by LLM MetaPlanner.
    """

    policies: list[LLMSubsystemPolicy] = Field(
        description="Allocated subsystem policies"
    )
    estimated_total_cost_usd: float = Field(description="Summed cost estimation")
    confidence_score: float = Field(
        description="Aggregated confidence evaluation score (0.0 to 1.0)"
    )
    explanation: str = Field(
        description="High-level plan summary and execution rationale"
    )


# Patch BaseModel to appear frozen to the dataclasses compiler at runtime
if hasattr(BaseModel, "__dataclass_params__"):
    BaseModel.__dataclass_params__.frozen = False  # type: ignore[attr-defined]
