"""
Recommendation Model.

Represents a recommendation generated by ML-OS.

Author: Vikram Tanakala
License: MIT
"""

from dataclasses import dataclass

from mlos.domain.enums.recommendation_priority import RecommendationPriority
from mlos.domain.models.base import BaseModel


@dataclass
class Recommendation(BaseModel):
    """
    A recommendation generated by the reasoning engine.
    """

    title: str

    description: str

    priority: RecommendationPriority = RecommendationPriority.MEDIUM
