from enum import Enum


class KnowledgeEntryType(str, Enum):
    """
    Structured categories of system knowledge entries.
    """

    HEURISTIC_WEIGHT = "HEURISTIC_WEIGHT"
    PARAMETER_PRIOR = "PARAMETER_PRIOR"
    GENERATOR_BLACKLIST = "GENERATOR_BLACKLIST"
    GENERATOR_WHITELIST = "GENERATOR_WHITELIST"
    MODEL_PREFERENCE = "MODEL_PREFERENCE"
    PIPELINE_PREFERENCE = "PIPELINE_PREFERENCE"
    EVALUATION_THRESHOLD = "EVALUATION_THRESHOLD"
