from enum import Enum


class LearningUpdateType(str, Enum):
    """
    Structured types of pipeline learning updates proposed by the Learning subsystem.
    """

    ADJUST_PARAM_PRIOR = "ADJUST_PARAM_PRIOR"
    BOOST_HEURISTIC_WEIGHT = "BOOST_HEURISTIC_WEIGHT"
    DECREASE_HEURISTIC_WEIGHT = "DECREASE_HEURISTIC_WEIGHT"
    DISABLE_GENERATOR = "DISABLE_GENERATOR"
    ENABLE_GENERATOR = "ENABLE_GENERATOR"
    BLACKLIST_MODEL = "BLACKLIST_MODEL"
    WHITELIST_MODEL = "WHITELIST_MODEL"
    UPDATE_THRESHOLD = "UPDATE_THRESHOLD"
    REGISTER_PATTERN = "REGISTER_PATTERN"
